package instance_Sanitysuite;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import io.testproject.proxy.addon.ElementExtensions;
import io.testproject.proxy.addon.io.testproject.addons.element.web.DoubleClickWeb;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

/**
 * This class was automatically generated by TestProject
 * Project: Nutshell automation
 * Test: Folder path to Mobile Apps
 * Generated by: Saranya Shanmugam (Saranya.Shanmugam@nutshellapps.co.uk)
 * Generated on Sun Nov 01 00:53:05 GMT 2020.
 */
@Test(
    name = "Folder path to Mobile Apps",
    description = "This test was auto generated from steps of the 'Instance - Sanity tests' test",
    version = "1.0"
)
public class Apps_container_mobile implements WebTest {
  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;
    ExecutionResult executionresult;
    DoubleClickWeb doubleClickWeb;

    // 1. Click 'Apps'
    by = By.xpath("//a[. = 'Apps']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Apps'", booleanResult, TakeScreenshotConditionType.Failure);

  //8. Click qa review 
    Actions ac = new Actions(driver);  
    WebElement qareview = driver.findElement(by.id("folder_675"));
    ac.doubleClick(qareview).perform();
    report.step("Click 'DIV'", booleanResult, TakeScreenshotConditionType.Failure);
        
    //9. container sanity
    WebElement containersanity = driver.findElement(by.id("folder_704"));
    ac.doubleClick(containersanity).perform();
    report.step("Click 'DIV'", booleanResult, TakeScreenshotConditionType.Failure);    
    
    //10. mobile folder
    WebElement mobile = driver.findElement(by.id("folder_717"));
    ac.doubleClick(mobile).perform(); 

    return ExecutionResult.PASSED;
  }
}
