package instance_Sanitysuite;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: Nutshell automation
 * Test: Instance - Sanity tests
 * Generated by: Saranya Shanmugam (Saranya.Shanmugam@nutshellapps.co.uk)
 * Generated on Sun Nov 01 00:53:05 GMT 2020.
 */
@Test(
    name = "Instance - Sanity tests",
    version = "1.0"
)
public class InstanceSanityTests implements WebTest {
  /*@Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://qa.internal.nutshellapps.com/eDocs-Accounts/User/Login",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  @Parameter(
      defaultValue = "container.sanity@auto.nutshellapps.co.uk",
      direction = ParameterDirection.INPUT
  )
  public String username;

  @Parameter(
		  defaultValue = "P455.word12",
	      direction = ParameterDirection.INPUT
  )
  public String password;*/

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    OfflineCompare mobapp07offlinecompare;
    Onlineapp mobapp05online;
    Livemode mobapp03live;
    Newapp mobapp10warmsynctest;
    Updatedapp mobapp09updatedapp;
    Session mobapp12session;
    Previewmode mobapp01preview;
    Testmode mobapp02test;
    Login login;
    boolean booleanResult;
    Apps_container_mobile folderpathtomobileapps;
    Offlineapp mobapp06offline;
    ExecutionResult executionresult;
    Inaccessible mobapp08inaccessible;
    Newtables mobapp11newtables;
    Allmodes mobapp04allmodes;

    // 1. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    login = new Login();
    //login.ApplicationURL = ApplicationURL;
  //  login.username = username;
   // login.password = password;
    executionresult = login.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 2. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 3. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp01preview = new Previewmode();
    executionresult = mobapp01preview.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 4. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 5. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp02test = new Testmode();
    executionresult = mobapp02test.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 6. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 7. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp03live = new Livemode();
    executionresult = mobapp03live.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 8. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 9. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp04allmodes = new Allmodes();
    executionresult = mobapp04allmodes.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 10. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 11. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp05online = new Onlineapp();
    executionresult = mobapp05online.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 12. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 13. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp06offline = new Offlineapp();
    executionresult = mobapp06offline.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 14. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 15. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp07offlinecompare = new OfflineCompare();
    executionresult = mobapp07offlinecompare.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 16. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 17. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp08inaccessible = new Inaccessible();
    executionresult = mobapp08inaccessible.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 18. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 19. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp09updatedapp = new Updatedapp();
    executionresult = mobapp09updatedapp.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 20. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 21. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp10warmsynctest = new Newapp();
    executionresult = mobapp10warmsynctest.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 22. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 23. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp11newtables = new Newtables();
    executionresult = mobapp11newtables.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 24. This test was auto generated from steps of the 'Instance - Sanity tests' test
    folderpathtomobileapps = new Apps_container_mobile();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 25. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp12session = new Session();
    executionresult = mobapp12session.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 26. Click 'Logout'
    by = By.cssSelector("#logoutDash");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Logout'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
