package instance_Sanitysuite;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class NutshellAutomationRunner {
  public static String developerToken = "BVdxeddYcKDmy7hZvcrbFep-wrPl8PsJao56fqHts04";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runInstanceSanityTests();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "InstanceSanityTests"
   */
    public static StepExecutionResult runInstanceSanityTests() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new InstanceSanityTests(), true);
  }

  /**
   * Runs "Login"
   */
    public static StepExecutionResult runLogin() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Login(), true);
  }

  /**
   * Runs "FolderPathToMobileApps"
   */
    public static StepExecutionResult runFolderPathToMobileApps() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Apps_container_mobile(), true);
  }

  /**
   * Runs "MobApp01preview"
   */
    public static StepExecutionResult runMobApp01preview() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Previewmode(), true);
  }

  /**
   * Runs "MobApp02test"
   */
    public static StepExecutionResult runMobApp02test() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Testmode(), true);
  }

  /**
   * Runs "MobApp03live"
   */
    public static StepExecutionResult runMobApp03live() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Livemode(), true);
  }/*

  /**
   * Runs "MobApp04allModes"
   */
    public static StepExecutionResult runMobApp04allModes() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Allmodes(), true);
  }

  /**
   * Runs "MobApp05online"
   */
    public static StepExecutionResult runMobApp05online() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Onlineapp(), true);
  }

  /**
   * Runs "MobApp06offline"
   */
    public static StepExecutionResult runMobApp06offline() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Offlineapp(), true);
  }

  /**
   * Runs "MobApp07offlineCompare"
   */
    public static StepExecutionResult runMobApp07offlineCompare() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new OfflineCompare(), true);
  }

  /**
   * Runs "MobApp08inaccessible"
   */
    public static StepExecutionResult runMobApp08inaccessible() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Inaccessible(), true);
  }

  /**
   * Runs "MobApp09updatedApp"
   */
    public static StepExecutionResult runMobApp09updatedApp() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Updatedapp(), true);
  }

  /**
   * Runs "MobApp10warmsyncTest"
   */
  public static StepExecutionResult runMobApp10warmsyncTest() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Newapp(), true);
  }

  /**
   * Runs "MobApp11newTables"
   */
  public static StepExecutionResult runMobApp11newTables() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Newtables(), true);
  }

  /**
   * Runs "MobApp12session"
   */
  public static StepExecutionResult runMobApp12session() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Session(), true);
  }
}
