package instance_Sanitysuite;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import io.testproject.proxy.addon.ElementExtensions;
import io.testproject.proxy.addon.io.testproject.addons.element.web.DoubleClickNoJs;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: Nutshell automation
 * Test: Mob App 02 (Test)
 * Generated by: Saranya Shanmugam (Saranya.Shanmugam@nutshellapps.co.uk)
 * Generated on Sun Nov 01 02:30:54 GMT 2020.
 */
@Test(
    name = "Mob App 02 (Test)",
    description = "This test was auto generated from steps of the 'Instance - Sanity tests' test",
    version = "1.0"
)
public class Testmode implements WebTest {
  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(30000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;
    ExecutionResult executionresult;
    DoubleClickNoJs doubleClickNoJs;

    // 1. Double Click 'DIV4'
    doubleClickNoJs = ElementExtensions.getDoubleClickNoJs();
    by = By.id("microapp_2682");
    executionresult = helper.executeProxy(doubleClickNoJs, by);
    report.step("Double Click 'DIV4'", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 2. Click 'Publish'
    by = By.cssSelector("#workflow_publish");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Publish'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Click 'rest_data_format'
    //    Test mode
    by = By.xpath("//div[4]/div/div/div/div[2]/div[1]/input");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'rest_data_format'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Click 'CONTINUE'
    //    confirm to publish(Test mode)
    by = By.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'CONTINUE'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Click 'CONTINUE'
    //    confirm - username selected
    by = By.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'CONTINUE'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Click 'name'
    //    Build information
    by = By.cssSelector("#name");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Type 'test mode' in 'name'
    //    Build information
    by = By.cssSelector("#name");
    booleanResult = driver.testproject().typeText(by,"test mode");
    report.step("Type 'test mode' in 'name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Click 'CONTINUE'
    by = By.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'CONTINUE'", booleanResult, TakeScreenshotConditionType.Failure);
    
    // 9. 'DIV10' contains text 'Successfully published to the Test community'?
    by = By.xpath("//body/div[4]/div/div");
    booleanResult = driver.testproject().containsText(by,"Successfully published");
    report.step("'DIV10' contains text 'Successfully published'?", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Click 'DIV'
    by = By.cssSelector("#workflow-back");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'DIV'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Click 'workflow-back2'
    by = By.cssSelector("#workflow-back");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow-back2'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Click 'workflow_back_confirm1'
    by = By.cssSelector("#workflow_back_confirm");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow_back_confirm1'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
