package trialinstance_Sanity_Oneapp;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: Nutshell automation (one app)
 * Test: Instance Sanity tests
 * Generated by: Saranya Shanmugam (Saranya.Shanmugam@nutshellapps.co.uk)
 * Generated on Sun Nov 01 00:08:57 GMT 2020.
 */
@Test(
    name = "Instance Sanity tests",
    version = "1.0"
)
public class InstanceSanityTests implements WebTest {
 /* @Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://qa.internal.nutshellapps.com/eDocs-Accounts/User/Login",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  @Parameter(
      defaultValue = "saranya.shanmugam@nutshellapps.co.uk",
      direction = ParameterDirection.INPUT
  )
  public String username;

  @Parameter(
      defaultValue = "Saranya123$$",
      direction = ParameterDirection.INPUT
  )
  public String password;*/

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    MobApp01preview mobapp01preview;
    boolean booleanResult;
    Login login;
    ExecutionResult executionresult;
    FolderPathToMobileApps folderpathtomobileapps;

    // 1. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    login = new Login();
  //  login.Applicationurl = ApplicationURL;
   // login.username = username;
   // login.password = password;
    executionresult = login.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 2. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    folderpathtomobileapps = new FolderPathToMobileApps();
    executionresult = folderpathtomobileapps.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 3. This test was auto generated from steps of the 'Instance - Sanity tests' test
    //    This step was auto generated from several steps
    mobapp01preview = new MobApp01preview();
    executionresult = mobapp01preview.execute(helper);
    report.step("This test was auto generated from steps of the 'Instance - Sanity tests' test", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 4. Click 'Logout'
    by = By.cssSelector("#logoutDash");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Logout'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
