package trialinstance_Sanity_Oneapp;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import io.testproject.proxy.addon.ElementExtensions;
import io.testproject.proxy.addon.io.testproject.addons.element.web.DoubleClickNoJs;
import io.testproject.proxy.addon.io.testproject.addons.element.web.DoubleClickWeb;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

/**
 * This class was automatically generated by TestProject
 * Project: Nutshell automation (one app)
 * Test: Mob App 01 (preview)
 * Generated by: Saranya Shanmugam (Saranya.Shanmugam@nutshellapps.co.uk)
 * Generated on Sun Nov 01 00:08:57 GMT 2020.
 */
@Test(
    name = "Mob App 01 (preview)",
    description = "This test was auto generated from steps of the 'Instance - Sanity tests' test",
    version = "1.0"
)
public class MobApp01preview implements WebTest {
  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(30000);
    TestReporter report = helper.getReporter();
    By by = null;
    boolean booleanResult;
    ExecutionResult executionresult;
    DoubleClickNoJs doubleClickNoJs;
    DoubleClickWeb doubleClickWeb;

  //11. mobile app 001 builder
    Actions ac1 = new Actions(driver);  
    WebElement app001 = driver.findElement(By.id("microapp_2681"));
    ac1.doubleClick(app001).perform();   
    
    
    //12. Click 'workflow_publish'
    by = by.cssSelector("#workflow_publish");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow_publish'", booleanResult, TakeScreenshotConditionType.Failure);

    //13. Click 'Private publishing mode screen' - test users
    by = by.xpath("//div[4]/div/div/div/div[2]/div[1]/input");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'rest_data_format'", booleanResult, TakeScreenshotConditionType.Failure);

    //14. Click 'continue'
    by = by.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'yes'", booleanResult, TakeScreenshotConditionType.Failure);

    //15. Click 'Publish list users'
    by = by.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'yes'", booleanResult, TakeScreenshotConditionType.Failure);

    //16.  Click 'continue'
    by = by.cssSelector("#yes");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'yes'", booleanResult, TakeScreenshotConditionType.Failure);

    //17.  Click 'publish'
    by = by.xpath("//body/div[3]");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'DIV4'", booleanResult, TakeScreenshotConditionType.Failure);
    
 // 7. 'DIV10' contains text 'Successfully published to the Test community'?
    by = By.xpath("//body/div[4]/div/div");
    booleanResult = driver.testproject().containsText(by,"Successfully published");
    report.step("'DIV10' contains text 'Successfully published'?", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. 'DIV10' contains text 'This will be available next time their apps are synchronised.'?
    by = By.xpath("//body/div[4]/div/div");
    booleanResult = driver.testproject().containsText(by,"This will be available next time their apps are synchronised.");
    report.step("'DIV10' contains text 'This will be available next time their apps are synchronised.'?", booleanResult, TakeScreenshotConditionType.Failure);


    //18.  Click 'click on anywhere in screen to enable builder'
    by = by.cssSelector("#workflow-back");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow-back'", booleanResult, TakeScreenshotConditionType.Failure);
    
    //19. Display Go back to folder and apps screen     
    by = by.cssSelector("#workflow-back");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow-back'", booleanResult, TakeScreenshotConditionType.Failure);
    
    // 20. Click 'workflow_back_confirm'
    by = by.cssSelector("#workflow_back_confirm");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'workflow_back_confirm'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
