package trialinstance_Sanity_Oneapp;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class NutshellAutomationoneAppRunner {
  public static String developerToken = "BVdxeddYcKDmy7hZvcrbFep-wrPl8PsJao56fqHts04";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runInstanceSanityTests();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "InstanceSanityTests"
   */
  public static StepExecutionResult runInstanceSanityTests() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new InstanceSanityTests(), true);
  }

  /**
   * Runs "Login"
   */
  public static StepExecutionResult runLogin() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new Login(), true);
  }

  /**
   * Runs "FolderPathToMobileApps"
   */
  public static StepExecutionResult runFolderPathToMobileApps() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new FolderPathToMobileApps(), true);
  }

  /**
   * Runs "MobApp01preview"
   */
  public static StepExecutionResult runMobApp01preview() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new MobApp01preview(), true);
  }
}
